// === src/main/webapp/app/entities/task/task.model.ts ===
import dayjs from 'dayjs';
import { IUser } from 'app/entities/user/user.model';
import { TaskStatus } from 'app/shared/model/enumerations/task-status.model';
import { Priority } from 'app/shared/model/enumerations/priority.model'; // Assuming Priority enum exists
import { ICategory } from 'app/entities/category/category.model'; // Assuming category model path

export interface ITask {
  id: number;
  title?: string | null;
  description?: string | null;
  dueDate?: dayjs.Dayjs | null;
  status?: TaskStatus | null;
  priority?: Priority | null;
  createdDate?: dayjs.Dayjs | null;
  lastModifiedDate?: dayjs.Dayjs | null;
  assignee?: IUser | null; // Added missing 'assignee' property
  category?: ICategory | null; // Added missing 'category' property
}

export type NewTask = Omit<ITask, 'id'> & { id: null };

// This utility type is typically generated by JHipster and often used in form services.
// Ensure it's defined in task.model.ts or a shared utility file.
export type PartialWithRequiredKeyOf<T extends { id: unknown }, K extends keyof T> = Partial<Omit<T